name: tititata
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  cached_network_image: ^3.3.1
  timeago: ^3.6.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  http: ^1.1.0
  photo_view: ^0.14.0
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  gal: ^2.2.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
